spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-ancient-cloud-apqixqmj-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TZUXQbfvkl71

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect